version: '2'

services:
  avalon:
    build: 
      context: ./avalon
      args:
        - AVALON_BRANCH
        - DATABASE_URL
        - SECRET_KEY_BASE
        - BASE_URL
        - ASSET_HOST
    image: 039358184980.dkr.ecr.us-west-2.amazonaws.com/avalon:latest 
    mem_limit: 1000000000
    environment:
      - APP_NAME
      - SECRET_KEY_BASE
      - BASE_URL
      - CONTROLLED_VOCABULARY
      - DATABASE_URL
      - DROPBOX_PATH
      - DROPBOX_URI
      - EMAIL_COMMENTS
      - EMAIL_NOTIFICATION
      - EMAIL_SUPPORT
      - FEDORA_NAMESPACE
      - FEDORA_URL
      - FFMPEG_PATH
      - MASTER_FILE_PATH
      - MASTER_FILE_STRATEGY
      - MATTERHORN_URL
      - MEDIAINFO_PATH
      - RAILS_ENV
      - SMTP_ADDRESS
      - SMTP_AUTHENTICATION
      - SMTP_DOMAIN
      - SMTP_ENABLE_STARTTLS_AUTO
      - SMTP_OPENSSL_VERIFY_MODE
      - SMTP_PASSWORD
      - SMTP_PORT
      - SMTP_USER_NAME
      - SOLR_URL
      - STREAM_BASE
      - STREAM_DEFAULT_QUALITY
      - STREAM_HTTP_BASE
      - STREAM_RTMP_BASE
      - STREAM_SERVER
      - STREAM_TOKEN_TTL
      - SYSTEM_GROUPS
      - Z3950_ATTRIBUTE
      - Z3950_DATABASE
      - Z3950_HOST
      - Z3950_PORT
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_REGION
      - AWS_PIPELINE_ID
      - S3_BUCKET
      - S3_UPLOAD_PREFIX
      - S3_OUTPUT_PREFIX
      - CLOUDFRONT_KEYFILE 
    env_file: 
      - .env
    volumes:
      - /masterfiles:/masterfiles
      - /gems:/gems
    ports:
      - "80:80"
